name: saumilp.github.io
markdown: redcarpet
highlighter: null
permalink: /:title

url: http://saumilp.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed