name: saumilp.github.io
markdown: redcarpet
highlighter: rouge
permalink: /:title

url: http://saumilp.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
