# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
#highlighter:      pygments
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            codeground
tagline:          'coding.isFun()'
description:      'Code, Thoughts and Ideas'
url:              saumilp.github.io
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Saumil Patel'
  url:            saumilp.github.io

# Social Integration
social:
  twitter:        SaumilP10
  disqus:         SaumilP
  addthis_pubid:  ra-54cdd2703320cb27

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:     UA-59409595-1 
  super_proxy_url:  

# Github
github:
  repo:           https://github.com/SaumilP
  feedback:       

# Version Info
# version:          0.0.1
