name: Build and deploy Zola site on GitHub Pages
on:
   push:
     branches:
        - master
jobs:
   build:
      name: Publish site
      runs-on: ubuntu-latest
      steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Zola Deploy
        uses: zbrox/zola-deploy-action@0.12.2
        env:
          TOKEN: ${{ secrets.TOKEN }}
          
