name: Build and deploy Zola site on GitHub Pages
on:
   push:
     branches:
        - master
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false
  

jobs:
   # Deploy job
   build:
      name: Publish site
      runs-on: ubuntu-latest
      steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Zola Deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          TOKEN: ${{ secrets.TOKEN }}
          
